version: "3.9"
services:
  sql_server:
    container_name: p2p_shopping_sql_server
    restart: always
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      SA_PASSWORD: "nH2nNC93A8D"
      ACCEPT_EULA: "Y"
    volumes:
      - vol_db:/var/opt/mssql
    expose:
      - 1433

  backend_service:
    container_name: p2p_shopping_backend_service
    depends_on: 
      - sql_server
    restart: always
    build:
      context: .
      dockerfile: ./BackendService/Dockerfile
    volumes:
      - backend_service_volume:/app 
    ports:
      - "8080:80"
      - "8081:443"

volumes:
  vol_db:
    driver: local
  backend_service_volume:
    driver: local