version: "3.9"
services:
  sql_server:
    container_name: p2p_shopping_sql_server
    restart: always
    image: "mcr.microsoft.com/azure-sql-edge"
    environment:
      SA_PASSWORD: "nH2nNC93A8D"
      ACCEPT_EULA: "Y"
    volumes:
      - vol_db:/var/opt/mssql
    ports:
      - "9999:1433" 

volumes:
  vol_db:
    driver: local